--- #YAML:1.0
name: Net-DAAP-DMAP-Pack
version: 1.20
author:
  - Richard Clamp <richardc@unixbeard.net>
abstract: Write DMAP encoded data
license: perl
requires:
  Math::BigInt: 0
  Net::DAAP::DMAP: 0
  perl: 5.006
build_requires:
  Test::More: 0
provides:
  Net::DAAP::DMAP::Pack:
    file: lib/Net/DAAP/DMAP/Pack.pm
    version: 1.20
generated_by: Module::Build version 0.25
